export interface Player {
  id: number
  name: string
  role: string
  country: string
  age: number
  basePrice: number
  battingStyle: string
  bowlingStyle: string
  image: string
  specialSkills: string[]
  isHidden?: boolean
  isStealCard?: boolean
}

// Batsmen (20 players, 1 hidden)
const batsmen: Player[] = [
  {
    id: 1,
    name: "Virat Kohli",
    role: "Batsman",
    country: "India",
    age: 35,
    basePrice: 20000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/virat-kohli-cricket-player.jpg",
    specialSkills: ["Chase Master", "Captain", "Aggressive Batting"],
    isHidden: true, // Hidden batsman
  },
  {
    id: 2,
    name: "Rohit Sharma",
    role: "Batsman",
    country: "India",
    age: 36,
    basePrice: 16000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/rohit-sharma-cricket-player.jpg",
    specialSkills: ["Opening", "Captain", "Big Hitter"],
  },
  {
    id: 3,
    name: "Babar Azam",
    role: "Batsman",
    country: "Pakistan",
    age: 29,
    basePrice: 15000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder-x0yiy.png",
    specialSkills: ["Consistent", "Captain", "Anchor"],
  },
  {
    id: 4,
    name: "Kane Williamson",
    role: "Batsman",
    country: "New Zealand",
    age: 33,
    basePrice: 14000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder-2vp1t.png",
    specialSkills: ["Captain", "Anchor", "Consistent"],
  },
  {
    id: 5,
    name: "Steve Smith",
    role: "Batsman",
    country: "Australia",
    age: 34,
    basePrice: 14000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder-9ccpf.png",
    specialSkills: ["Technique", "Captain", "Spin Bowling"],
  },
  {
    id: 6,
    name: "Joe Root",
    role: "Batsman",
    country: "England",
    age: 33,
    basePrice: 13000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder-kuvbv.png",
    specialSkills: ["Consistent", "Captain", "Anchor"],
  },
  {
    id: 7,
    name: "David Warner",
    role: "Batsman",
    country: "Australia",
    age: 37,
    basePrice: 12000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder-iqnbn.png",
    specialSkills: ["Opening", "Aggressive", "Big Hitter"],
  },
  {
    id: 8,
    name: "KL Rahul",
    role: "Batsman",
    country: "India",
    age: 31,
    basePrice: 11000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/kl-rahul-cricket-player.jpg",
    specialSkills: ["Opening", "Wicket-keeping", "Versatile"],
  },
  {
    id: 9,
    name: "Shubman Gill",
    role: "Batsman",
    country: "India",
    age: 24,
    basePrice: 10000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/shubman-gill-cricket-player.jpg",
    specialSkills: ["Opening", "Young Talent", "Consistent"],
  },
  {
    id: 10,
    name: "Shreyas Iyer",
    role: "Batsman",
    country: "India",
    age: 29,
    basePrice: 10000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Captain", "Middle Order", "Spin Player"],
  },
  {
    id: 11,
    name: "Suryakumar Yadav",
    role: "Batsman",
    country: "India",
    age: 33,
    basePrice: 12000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["360 Degree", "Middle Order", "Innovative"],
  },
  {
    id: 12,
    name: "Jason Roy",
    role: "Batsman",
    country: "England",
    age: 33,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Aggressive", "Power Play"],
  },
  {
    id: 13,
    name: "Tim David",
    role: "Batsman",
    country: "Australia",
    age: 27,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Finisher", "Big Hitter"],
  },
  {
    id: 14,
    name: "Shimron Hetmyer",
    role: "Batsman",
    country: "West Indies",
    age: 27,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Middle Order", "Aggressive"],
  },
  {
    id: 15,
    name: "Prithvi Shaw",
    role: "Batsman",
    country: "India",
    age: 24,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Aggressive", "Young Talent"],
  },
  {
    id: 16,
    name: "Ruturaj Gaikwad",
    role: "Batsman",
    country: "India",
    age: 27,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Captain", "Consistent"],
  },
  {
    id: 17,
    name: "Tilak Varma",
    role: "Batsman",
    country: "India",
    age: 21,
    basePrice: 4000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Middle Order", "Young Talent", "Spin Player"],
  },
  {
    id: 18,
    name: "Nitish Rana",
    role: "Batsman",
    country: "India",
    age: 30,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Middle Order", "Part-time Spin", "Versatile"],
  },
  {
    id: 19,
    name: "Tristan Stubbs",
    role: "Batsman",
    country: "South Africa",
    age: 23,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Middle Order", "Power Hitting", "Young Talent"],
  },
  {
    id: 20,
    name: "Mayank Agarwal",
    role: "Batsman",
    country: "India",
    age: 33,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Captain", "Aggressive"],
  },
]

// Bowlers (28 players, 1 hidden)
const bowlers: Player[] = [
  {
    id: 21,
    name: "Jasprit Bumrah",
    role: "Bowler",
    country: "India",
    age: 30,
    basePrice: 12000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Yorkers", "Death Bowling", "Unorthodox Action"],
    isHidden: true, // Hidden bowler
  },
  {
    id: 22,
    name: "Pat Cummins",
    role: "Bowler",
    country: "Australia",
    age: 30,
    basePrice: 15000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/pat-cummins-cricket-player.jpg",
    specialSkills: ["Captain", "Pace", "Bounce"],
  },
  {
    id: 23,
    name: "Kagiso Rabada",
    role: "Bowler",
    country: "South Africa",
    age: 28,
    basePrice: 14000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/placeholder-f39ou.png",
    specialSkills: ["Pace", "Swing", "Wicket-taker"],
  },
  {
    id: 24,
    name: "Trent Boult",
    role: "Bowler",
    country: "New Zealand",
    age: 34,
    basePrice: 12000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Swing", "New Ball", "Left-arm"],
  },
  {
    id: 25,
    name: "Mitchell Starc",
    role: "Bowler",
    country: "Australia",
    age: 34,
    basePrice: 12000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm fast",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Pace", "Yorkers", "Left-arm"],
  },
  {
    id: 26,
    name: "Rashid Khan",
    role: "Bowler",
    country: "Afghanistan",
    age: 25,
    basePrice: 14000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Leg Spin", "Variations", "Young Talent"],
  },
  {
    id: 27,
    name: "Yuzvendra Chahal",
    role: "Bowler",
    country: "India",
    age: 33,
    basePrice: 10000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Leg Spin", "Wicket-taker", "Middle Overs"],
  },
  {
    id: 28,
    name: "Sunil Narine",
    role: "Bowler",
    country: "West Indies",
    age: 35,
    basePrice: 8000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Mystery Spin", "Powerplay", "Opening"],
  },
  {
    id: 29,
    name: "Mohammed Shami",
    role: "Bowler",
    country: "India",
    age: 33,
    basePrice: 10000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Swing", "Seam", "Experience"],
  },
  {
    id: 30,
    name: "Bhuvneshwar Kumar",
    role: "Bowler",
    country: "India",
    age: 34,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Swing", "Death Bowling", "Experience"],
  },
  {
    id: 31,
    name: "Arshdeep Singh",
    role: "Bowler",
    country: "India",
    age: 24,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Death Bowling", "Left-arm", "Young Talent"],
  },
  {
    id: 32,
    name: "Adil Rashid",
    role: "Bowler",
    country: "England",
    age: 36,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Leg Spin", "Variations", "Experience"],
  },
  {
    id: 33,
    name: "Josh Hazlewood",
    role: "Bowler",
    country: "Australia",
    age: 33,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Line & Length", "Seam", "Consistent"],
  },
  {
    id: 34,
    name: "Adam Zampa",
    role: "Bowler",
    country: "Australia",
    age: 31,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Leg Spin", "Middle Overs", "Variations"],
  },
  {
    id: 35,
    name: "Anrich Nortje",
    role: "Bowler",
    country: "South Africa",
    age: 30,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Express Pace", "Bounce", "Wicket-taker"],
  },
  {
    id: 36,
    name: "Tabraiz Shamsi",
    role: "Bowler",
    country: "South Africa",
    age: 34,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Left-arm chinaman",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Spin", "Variations", "Wicket-taker"],
  },
  {
    id: 37,
    name: "Alzarri Joseph",
    role: "Bowler",
    country: "West Indies",
    age: 27,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Pace", "Bounce", "Wicket-taker"],
  },
  {
    id: 38,
    name: "Akeal Hosein",
    role: "Bowler",
    country: "West Indies",
    age: 30,
    basePrice: 4000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Spin", "Powerplay", "Economical"],
  },
  {
    id: 39,
    name: "Lockie Ferguson",
    role: "Bowler",
    country: "New Zealand",
    age: 32,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Express Pace", "Death Bowling", "Yorkers"],
  },
  {
    id: 40,
    name: "Kuldeep Yadav",
    role: "Bowler",
    country: "India",
    age: 29,
    basePrice: 8000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm chinaman",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Spin", "Variations", "Wicket-taker"],
  },
  {
    id: 41,
    name: "Mohammed Siraj",
    role: "Bowler",
    country: "India",
    age: 30,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Swing", "New Ball", "Aggressive"],
  },
  {
    id: 42,
    name: "Umran Malik",
    role: "Bowler",
    country: "India",
    age: 24,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Express Pace", "Young Talent", "Raw Speed"],
  },
  {
    id: 43,
    name: "Avesh Khan",
    role: "Bowler",
    country: "India",
    age: 27,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Death Bowling", "Variations", "Pace"],
  },
  {
    id: 44,
    name: "Harshal Patel",
    role: "Bowler",
    country: "India",
    age: 33,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Death Bowling", "Slower Balls", "Purple Cap Winner"],
  },
  {
    id: 45,
    name: "Reece Topley",
    role: "Bowler",
    country: "England",
    age: 30,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Pace", "Swing", "Height Advantage"],
  },
  {
    id: 46,
    name: "Mujeeb Ur Rahman",
    role: "Bowler",
    country: "Afghanistan",
    age: 23,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Mystery Spin", "Variations", "Young Talent"],
  },
  {
    id: 47,
    name: "Fazalhaq Farooqi",
    role: "Bowler",
    country: "Afghanistan",
    age: 23,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Pace", "Swing", "Young Talent"],
  },
  {
    id: 48,
    name: "Mustafizur Rahman",
    role: "Bowler",
    country: "Bangladesh",
    age: 28,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Pace", "Cutters", "Death Bowling"],
  },
]

// Wicket-keepers (11 players, 1 hidden)
const wicketKeepers: Player[] = [
  {
    id: 49,
    name: "MS Dhoni",
    role: "Wicket-keeper",
    country: "India",
    age: 42,
    basePrice: 12000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Finishing", "Captain Cool", "Lightning Stumping"],
    isHidden: true, // Hidden wicket keeper
  },
  {
    id: 50,
    name: "Jos Buttler",
    role: "Wicket-keeper",
    country: "England",
    age: 33,
    basePrice: 12000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Captain", "Aggressive", "Opening"],
  },
  {
    id: 51,
    name: "Rishabh Pant",
    role: "Wicket-keeper",
    country: "India",
    age: 26,
    basePrice: 14000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Aggressive", "Young Talent", "Match Winner"],
  },
  {
    id: 52,
    name: "Quinton de Kock",
    role: "Wicket-keeper",
    country: "South Africa",
    age: 31,
    basePrice: 10000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder-dczs2.png",
    specialSkills: ["Wicket-keeping", "Opening", "Aggressive"],
  },
  {
    id: 53,
    name: "Nicholas Pooran",
    role: "Wicket-keeper",
    country: "West Indies",
    age: 28,
    basePrice: 10000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Captain", "Aggressive"],
  },
  {
    id: 54,
    name: "Sanju Samson",
    role: "Wicket-keeper",
    country: "India",
    age: 29,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Captain", "Elegant", "Consistent"],
  },
  {
    id: 55,
    name: "Ishan Kishan",
    role: "Wicket-keeper",
    country: "India",
    age: 25,
    basePrice: 8000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Aggressive", "Young Talent"],
  },
  {
    id: 56,
    name: "Jonny Bairstow",
    role: "Wicket-keeper",
    country: "England",
    age: 34,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Aggressive", "Experience"],
  },
  {
    id: 57,
    name: "Devon Conway",
    role: "Wicket-keeper",
    country: "New Zealand",
    age: 32,
    basePrice: 8000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Consistent", "Wicket-keeping"],
  },
  {
    id: 58,
    name: "Heinrich Klaasen",
    role: "Wicket-keeper",
    country: "South Africa",
    age: 32,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Middle Order", "Finisher"],
  },
  {
    id: 59,
    name: "Phil Salt",
    role: "Wicket-keeper",
    country: "England",
    age: 27,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Aggressive", "Wicket-keeping"],
  },
]

// All-rounders (29 players, 2 hidden)
const allRounders: Player[] = [
  {
    id: 60,
    name: "Ben Stokes",
    role: "All-rounder",
    country: "England",
    age: 32,
    basePrice: 16000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Pace Bowling", "Match Winner"],
  },
  {
    id: 61,
    name: "Hardik Pandya",
    role: "All-rounder",
    country: "India",
    age: 30,
    basePrice: 15000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Death Bowling", "Fielding"],
  },
  {
    id: 62,
    name: "Andre Russell",
    role: "All-rounder",
    country: "West Indies",
    age: 35,
    basePrice: 12000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Death Bowling", "Big Hitter"],
  },
  {
    id: 63,
    name: "Liam Livingstone",
    role: "All-rounder",
    country: "England",
    age: 30,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Power Hitting", "Spin Bowling", "Big Hitter"],
    isHidden: true, // Hidden all-rounder
  },
  {
    id: 64,
    name: "Ravindra Jadeja",
    role: "All-rounder",
    country: "India",
    age: 35,
    basePrice: 12000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder-8zezy.png",
    specialSkills: ["Spin Bowling", "Fielding", "Lower Order"],
  },
  {
    id: 65,
    name: "Glenn Maxwell",
    role: "All-rounder",
    country: "Australia",
    age: 35,
    basePrice: 11000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder-hps70.png",
    specialSkills: ["Big Hitter", "Spin Bowling", "Versatile"],
  },
  {
    id: 66,
    name: "Shakib Al Hasan",
    role: "All-rounder",
    country: "Bangladesh",
    age: 37,
    basePrice: 10000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder-ggykj.png",
    specialSkills: ["Captain", "Spin Bowling", "Experience"],
  },
  {
    id: 67,
    name: "Marcus Stoinis",
    role: "All-rounder",
    country: "Australia",
    age: 34,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder-ocqhg.png",
    specialSkills: ["Power Hitting", "Death Bowling", "Fielding"],
  },
  {
    id: 68,
    name: "Moeen Ali",
    role: "All-rounder",
    country: "England",
    age: 36,
    basePrice: 8000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder-5pqo1.png",
    specialSkills: ["Spin Bowling", "Lower Order", "Experience"],
  },
  {
    id: 69,
    name: "Kieron Pollard",
    role: "All-rounder",
    country: "West Indies",
    age: 36,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder-zy0y5.png",
    specialSkills: ["Power Hitting", "Captain", "Experience"],
  },
  {
    id: 70,
    name: "Dwayne Bravo",
    role: "All-rounder",
    country: "West Indies",
    age: 40,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder-urj11.png",
    specialSkills: ["Death Bowling", "Lower Order", "Experience"],
  },
  {
    id: 71,
    name: "Washington Sundar",
    role: "All-rounder",
    country: "India",
    age: 24,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Spin Bowling", "Lower Order", "Young Talent"],
  },
  {
    id: 72,
    name: "Sam Curran",
    role: "All-rounder",
    country: "England",
    age: 25,
    basePrice: 10000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Death Bowling", "Lower Order", "Left-arm"],
  },
  {
    id: 73,
    name: "Aiden Markram",
    role: "All-rounder",
    country: "South Africa",
    age: 29,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Captain", "Opening", "Spin Bowling"],
  },
  {
    id: 74,
    name: "Mitchell Santner",
    role: "All-rounder",
    country: "New Zealand",
    age: 32,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Spin", "Lower Order", "Captain"],
  },
  {
    id: 75,
    name: "Wanindu Hasaranga",
    role: "All-rounder",
    country: "Sri Lanka",
    age: 26,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Leg Spin", "Lower Order", "Captain"],
  },
  {
    id: 76,
    name: "Dasun Shanaka",
    role: "All-rounder",
    country: "Sri Lanka",
    age: 32,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Captain", "Power Hitting", "Death Bowling"],
  },
  {
    id: 77,
    name: "Abhishek Sharma",
    role: "All-rounder",
    country: "India",
    age: 23,
    basePrice: 4000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Left-arm Spin", "Young Talent"],
  },
  {
    id: 78,
    name: "Riyan Parag",
    role: "All-rounder",
    country: "India",
    age: 22,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm leg-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Middle Order", "Leg Spin", "Young Talent"],
  },
  {
    id: 79,
    name: "Venkatesh Iyer",
    role: "All-rounder",
    country: "India",
    age: 29,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Part-time Bowling", "Versatile"],
  },
  {
    id: 80,
    name: "Deepak Hooda",
    role: "All-rounder",
    country: "India",
    age: 29,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Middle Order", "Part-time Spin", "Versatile"],
  },
  {
    id: 81,
    name: "Krunal Pandya",
    role: "All-rounder",
    country: "India",
    age: 33,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Spin", "Lower Order", "Experience"],
  },
  {
    id: 82,
    name: "Axar Patel",
    role: "All-rounder",
    country: "India",
    age: 30,
    basePrice: 8000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Spin", "Lower Order", "Economical"],
  },
  {
    id: 83,
    name: "Will Jacks",
    role: "All-rounder",
    country: "England",
    age: 25,
    basePrice: 6000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Spin Bowling", "Young Talent"],
  },
  {
    id: 84,
    name: "Marco Jansen",
    role: "All-rounder",
    country: "South Africa",
    age: 24,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Left-arm Pace", "Height", "Lower Order"],
  },
  {
    id: 85,
    name: "Rachin Ravindra",
    role: "All-rounder",
    country: "New Zealand",
    age: 24,
    basePrice: 6000000,
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Left-arm Spin", "Young Talent"],
  },
  {
    id: 86,
    name: "Finn Allen",
    role: "All-rounder",
    country: "New Zealand",
    age: 24,
    basePrice: 4000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Aggressive", "Young Talent"],
  },
  {
    id: 87,
    name: "Ibrahim Zadran",
    role: "All-rounder",
    country: "Afghanistan",
    age: 22,
    basePrice: 2000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Opening", "Young Talent", "Consistent"],
  },
  {
    id: 88,
    name: "Jason Holder",
    role: "All-rounder",
    country: "West Indies",
    age: 32,
    basePrice: 8000000,
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast-medium",
    image: "/placeholder.svg?height=300&width=300",
    specialSkills: ["Captain", "Height", "Experience"],
  },
]

// Steal Cards (3 special cards)
const stealCards: Player[] = [
  {
    id: 89,
    name: "STEAL CARD",
    role: "Special",
    country: "Universal",
    age: 0,
    basePrice: 0,
    battingStyle: "N/A",
    bowlingStyle: "N/A",
    image: "/golden-steal-card.jpg",
    specialSkills: ["Steal any player from opponent", "One-time use", "Game changer"],
    isStealCard: true,
  },
  {
    id: 90,
    name: "STEAL CARD",
    role: "Special",
    country: "Universal",
    age: 0,
    basePrice: 0,
    battingStyle: "N/A",
    bowlingStyle: "N/A",
    image: "/golden-steal-card.jpg",
    specialSkills: ["Steal any player from opponent", "One-time use", "Game changer"],
    isStealCard: true,
  },
  {
    id: 91,
    name: "STEAL CARD",
    role: "Special",
    country: "Universal",
    age: 0,
    basePrice: 0,
    battingStyle: "N/A",
    bowlingStyle: "N/A",
    image: "/golden-steal-card.jpg",
    specialSkills: ["Steal any player from opponent", "One-time use", "Game changer"],
    isStealCard: true,
  },
]

function shuffleCardsWithDistribution(allPlayers: Player[]): Player[] {
  // Separate regular players and special cards
  const regularPlayers = allPlayers.filter((p) => !p.isStealCard)
  const specialCards = allPlayers.filter((p) => p.isStealCard)

  // Shuffle regular players
  const shuffledRegular = [...regularPlayers].sort(() => Math.random() - 0.5)

  // Calculate positions for special cards (evenly distributed)
  const totalCards = allPlayers.length
  const specialPositions = []
  const interval = Math.floor(totalCards / (specialCards.length + 1))

  for (let i = 1; i <= specialCards.length; i++) {
    specialPositions.push(interval * i + Math.floor(Math.random() * 5) - 2) // Add some randomness
  }

  // Insert special cards at calculated positions
  const result = [...shuffledRegular]
  specialPositions.forEach((pos, index) => {
    const adjustedPos = Math.max(0, Math.min(pos, result.length))
    result.splice(adjustedPos, 0, specialCards[index])
  })

  return result
}

export function getAllPlayersWithStealCards(): Player[] {
  const allPlayers = [...batsmen, ...bowlers, ...wicketKeepers, ...allRounders]
  const totalCards = allPlayers.length + stealCards.length // 88 + 3 = 91
  const result: Player[] = []

  // Calculate positions for steal cards (evenly distributed)
  const stealPositions = [
    Math.floor(totalCards * 0.25), // Around 25%
    Math.floor(totalCards * 0.5), // Around 50%
    Math.floor(totalCards * 0.75), // Around 75%
  ]

  let playerIndex = 0
  let stealIndex = 0

  for (let i = 0; i < totalCards; i++) {
    if (stealPositions.includes(i) && stealIndex < stealCards.length) {
      result.push(stealCards[stealIndex])
      stealIndex++
    } else if (playerIndex < allPlayers.length) {
      result.push(allPlayers[playerIndex])
      playerIndex++
    }
  }

  return result
}

export const createRoundBasedPlayers = () => {
  // Get all regular players (excluding steal cards)
  const regularPlayers = [
    ...batsmen, // 20 players
    ...bowlers, // 28 players
    ...wicketKeepers, // 11 players
    ...allRounders, // 29 players
  ] // Total: 88 players

  // Shuffle the regular players to ensure random distribution
  const shuffledPlayers = [...regularPlayers].sort(() => Math.random() - 0.5)

  // Distribute players across rounds with good mix of roles
  const round1Players: Player[] = []
  const round2Players: Player[] = []
  const round3Players: Player[] = []

  // Separate players by role for balanced distribution
  const batsmenPool = shuffledPlayers.filter((p) => p.role === "Batsman")
  const bowlersPool = shuffledPlayers.filter((p) => p.role === "Bowler")
  const keepersPool = shuffledPlayers.filter((p) => p.role === "Wicket-keeper")
  const allRoundersPool = shuffledPlayers.filter((p) => p.role === "All-rounder")

  // Distribute batsmen (20 total: 7, 7, 6)
  round1Players.push(...batsmenPool.slice(0, 7))
  round2Players.push(...batsmenPool.slice(7, 14))
  round3Players.push(...batsmenPool.slice(14, 20))

  // Distribute bowlers (28 total: 10, 10, 8)
  round1Players.push(...bowlersPool.slice(0, 10))
  round2Players.push(...bowlersPool.slice(10, 20))
  round3Players.push(...bowlersPool.slice(20, 28))

  // Distribute wicket-keepers (11 total: 4, 4, 3)
  round1Players.push(...keepersPool.slice(0, 4))
  round2Players.push(...keepersPool.slice(4, 8))
  round3Players.push(...keepersPool.slice(8, 11))

  // Distribute all-rounders (29 total: 9, 9, 11)
  round1Players.push(...allRoundersPool.slice(0, 9))
  round2Players.push(...allRoundersPool.slice(9, 18))
  round3Players.push(...allRoundersPool.slice(18, 29))

  // Add 1 steal card to each round
  const round1WithSteal = shuffleCardsWithDistribution([...round1Players, stealCards[0]])
  const round2WithSteal = shuffleCardsWithDistribution([...round2Players, stealCards[1]])
  const round3WithSteal = shuffleCardsWithDistribution([...round3Players, stealCards[2]])

  return {
    round1: round1WithSteal, // 31 cards (30 players + 1 steal)
    round2: round2WithSteal, // 31 cards (30 players + 1 steal)
    round3: round3WithSteal, // 29 cards (28 players + 1 steal)
  }
}

// Export categories for easy access
export const playerCategories = {
  batsmen,
  bowlers,
  wicketKeepers,
  allRounders,
  stealCards,
}
